services:
    nginx:
        image: nginx:stable-alpine
        container_name: gb-app-webserver
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        restart: unless-stopped
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                XDEBUG: 0
                PHP_IDE_CONFIG: "serverName=gb-app.test"
        container_name: gb-app-php
        volumes:
            - ./:/var/www/html
        restart: unless-stopped
        depends_on:
            - db
    db:
        image: mysql:5.7
        container_name: gb-app-db
        environment:
            MYSQL_ROOT_PASSWORD: passwordr
            MYSQL_DATABASE: GBapp
            MYSQL_USER: pcadmin
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        restart: unless-stopped

volumes:
    db_data:
